### ISSUE TITLE
Error initializing Iris, ubuntu, neovim.

### ISSUE THREAD

**Issue by mmngreco** [soywod/iris.vim#1]
Hi there,

First, I would like to congratulate you about this interesting project
which is exactly what I looking for. Sadly, I could'n make it work, I found some
problems initializing `Iris`. I added the follows in my vim config:

```
" ===== email : Iris
let g:iris_email = "user@enterprise.com"
let g:iris_name = "Maximiliano Greco"
let g:iris_imap_host = "imap.gmail.com"
let g:iris_imap_port = 993
let g:iris_imap_login = "user"
```

When I run Iris asks me for IMAP password which is wrote correctly, then I get
the next messages:

```
Iris: logging in...
Iris: selecting folder...
Iris: server: 'b''[AUTHENTICATIONFAILED] Invalid credentials (Failure)'''
Iris: server: 'command SELECT illegal in state NONAUTH, only allowed in states AUTH, SELECTED'
E21: Cannot make changes, 'modifiable' is off
```

Have I done something wrong?

**Comment by soywod** [comment]
Hi @mmngreco,
Did you try to use a 3rd party app password? Google prevents to use his own gmail password, instead you need to declare a 3rd party app that will generate a random password, and it's this one you will have to put. See [their doc](https://support.google.com/accounts/answer/3466521?hl=en).
Let me know,

**Comment by mmngreco** [comment]
> Did you try to use a 3rd party app password? Google prevents to use his own gmail password, instead you need to declare a 3rd party app that will generate a random password, and it's this one you will have to put. See their doc.

That was very helpful, thanks! Now it works! I have some feedback may interest you, do you mind if a open a new issue for each one?

> PS: I'm glad you find my project interesting. I would like to spend more time on it. Just a simple question, how did you find it?

Yes, I found it from github. Some days ago I was looking for an email vim pluggin and the first option was Iris.

**Comment by soywod** [comment]
> That was very helpful, thanks! Now it works!

I'm glad it worked :)

> I have some feedback may interest you, do you mind if a open a new issue for each one?

Sure, feel free to open them! With great pleasure!

> Yes, I found it from github. Some days ago I was looking for an email vim pluggin and the first option was Iris.

Interesting, thank you!
