### ISSUE TITLE
Setting correct reply headers

### ISSUE THREAD

**Issue by icyphox** [soywod/iris.vim#19]
Hey @soywod, I'm following up on your comment https://github.com/soywod/iris.vim/issues/5#issuecomment-638984243. I figured a new issue would be a good place to discuss. 

So the reply doesn't work for that GitHub mail, because the `To` field isn't be set correctly. My current mail client sets the `To` field to `"soywod/iris.vim" <reply+AEG2RO2MYI4ERSQ3DNOVFH544UFJJEVBNHHCLCBFDA@reply.github.com>`, whereas Iris sets it to `<notifications@github.com>`. Perhaps the raw source of the mail would be of use to you?

**Comment by soywod** [comment]
I see, could you share the raw mail you receive from GitHub so we can analyse it and see which header I should use?

**Comment by icyphox** [comment]
Sure, yes. I've pastebinned it here: https://termbin.com/rgtx

Also, sidenote: it appears that _any_ `mail` document edited in Vim is being detected by Iris. As a result, when I hit `:w`, it "saves" it, despite not having come from Iris itself. My current mail client uses Vim to edit, and Iris is interfering with it, haha.

**Comment by icyphox** [comment]
If you see, you should be using the `Reply-To` header if it exists, and not default to `To`. In our case:
`Reply-To: "soywod/iris.vim" <reply+AEG2RO2QXFJADZTSYUPKP4V44UMALEVBNHHCLHEZIM@reply.github.com>`

**Comment by soywod** [comment]
> Also, sidenote: it appears that any mail document edited in Vim is being detected by Iris.

Oops xD it makes sense, since I use the file type `mail` directly. I don't know then how to ''inherit'' from it without overriding, I will dig.

> If you see, you should be using the Reply-To header if it exists, and not default to To.

Indeed, I'll make the change ASAP.

**Comment by soywod** [comment]
If fixed the `mail.vim` syntax issue (https://github.com/soywod/iris.vim/commit/6dd1455da3a1e302953b90647d9358afd9081d8a) thanks to [this post](https://vi.stackexchange.com/questions/20565/linking-a-filetype-to-a-syntax-file-of-a-different-name).

I also use the header `Reply-To` by default to reply (https://github.com/soywod/iris.vim/commit/6e2f257998f8962fb115a3dbc1902283879a77f6). If it does not exist then I take `From`. Let me know if all works as expected!
