### ISSUE TITLE
Move mail

### ISSUE THREAD

**Issue by soywod** [soywod/iris.vim#23]

**Comment by kropper** [comment]
yes, pretty please!

Please also include, e.g., FZF-based fuzzy selection of the IMAP target folder (I have 100's of folders!).

**Comment by soywod** [comment]
It's my next feature, I will let you know :)

**Comment by soywod** [comment]
I will try to integrate fzf for selecting folder first (https://github.com/soywod/iris.vim/issues/29), then I will apply to the move function.

**Comment by soywod** [comment]
@kropper I pushed sth about https://github.com/soywod/iris.vim/issues/29, could you check if it works well for you?
