### ISSUE TITLE
Cannot obtain mail from outlook/office365

### ISSUE THREAD

**Issue by seanrmurphy** [soywod/iris.vim#3]
I'm experimenting with Iris but fell at the first hurdle.

My Mail hosted is on office 365.

It seems the configuration data I provided is valid for login, but Iris is unable to retrieve
mail (see screenshot).

Not really sure how to proceed - the link given in the error message does not shed any
light on the issue for me.

I did a little bit of searching and found this issue:

https://github.com/mscdex/node-imap/issues/762

which indicates that the search patterns on hotmail/outlook (not sure if this applies to
office365) differ. I changed the search pattern to use `'1:'` instead of `'*'` in Iris as an
experiment but it did not solve the problem.

![Screenshot from 2020-05-29 10-11-54](https://user-images.githubusercontent.com/540360/83237070-e0626d00-a194-11ea-846e-2cb90174bc5f.png)

**Comment by soywod** [comment]
I will investigate with a fake outlook account and let you know.

**Comment by soywod** [comment]
From the [IMAP RFC 3501](https://tools.ietf.org/html/rfc3501#section-6.4.4), the `SEARCH` cmd accepts a range of msg UID:

>       <sequence set>
>         Messages with message sequence numbers corresponding to the
>         specified message sequence number set.

A [UID range](https://tools.ietf.org/html/rfc3501#section-6.4.8) is defined as two integers separated by a `:`. The special char `*` can replace only one of the two integers and indicate all UIDs that are greater or lower than the other integer. So according to the RFC, `*` is not a valid pattern (although it seems to be accepted by most of mail providers). To be valid, the pattern should be `1:*`, which I just changed it and it works perfectly. Do not hesitate to reopen the issue if it still fails.

**Comment by seanrmurphy** [comment]
Thanks for this - I missed the trailing `*` in my simple experiment.

I no longer get the same error so in a sense it works better; now I get a new error when retrieving the `INBOX` folder - I think it is due to the size of my inbox and it seems to be a v non-descript error from Microsoft:

https://github.com/mscdex/node-imap/issues/44

I added a few logging statements and the problem occurs in the `get_last_seq()` function - happy to help a bit with debugging this but I'd need to understand IMAP a little better.

![Screenshot from 2020-05-29 14-17-32](https://user-images.githubusercontent.com/540360/83258762-2af4e100-a1b7-11ea-8c2e-fa86fc9bed14.png)

**Comment by soywod** [comment]
`get_last_seq()` tries to retrieve the latest UID by selecting all UID and take the more recent. But seems not to be adapted to such situation with giant amount of emails (how many do you have?). Could you open a new issue since it's not related to the first one?
