### ISSUE TITLE
Error on sending mail

### ISSUE THREAD

**Issue by 097115** [soywod/iris.vim#31]
I get this error on send (I use Gmail):

    Send: {"success": false, "type": "send-email", "error": "append failed: [TRYCREATE] Folder doesn't exist. (Failure)"}

Message is sent but doesn't appear in the Sent Mail folder.

May be somehow related: https://github.com/mjs/imapclient/blob/a2fecef526ac6003c35c3f373b9c5382dceef7dc/imapclient/imapclient.py#L588 says `"[Gmail]/Sent Mail"` is a [depreciated format](https://developers.google.com/gmail/imap/imap-extensions#xlist_is_deprecated) but in Mutt, for example, this is exactly how I see it. So, maybe it tries to copy this sent mail to a wrong folder?

**Comment by soywod** [comment]
Could you give me the list of your folders? You can do so by doing `:IrisFolder` and check `/tmp/iris-api.log`.

**Comment by 097115** [comment]
> Could you give me the list of your folders?

Well, I certainly couldn't, that's just too much private info :)

But if we speak about SENT-related folder, then Iris, too, shows it as `[Gmail]/Sent Mail` (and no other instance of "sent" is present).

> it seems you miss one?

What do you mean?

**Comment by soywod** [comment]
> Well, I certainly couldn't, that's just too much private info :)

Don't worry I didn't want to get your private infos :D my aim is just to understand your problem and try to fix it.

> But if we speak about SENT-related folder, then Iris, too, shows it as [Gmail]/Sent Mail (and no other instance of "sent" is present).

It's what I needed. Iris saves in the [`Sent`](https://github.com/soywod/iris.vim/blob/master/api.py#L248) folder by default, it seems that you misses this folder. How come? I have both with my gmail (Sent and [Gmail]/Sent).

**Comment by 097115** [comment]
> How come?

Yeah, that's the question, indeed :).

Anyway, thanks for the link. Since the problem is on my side, I'm probably closing this?

**Comment by soywod** [comment]
Well, I could set the `sent` folder customizable. Let's see if other people encounter the same problem.
