### ISSUE TITLE
Formatting emails on preview?

### ISSUE THREAD

**Issue by 097115** [soywod/iris.vim#32]
When appending emails to the preview buffer, `call append(0, split(email, "\n"))` does nothing to format them, and therefore long lines don't split and may be not so pleasant to read.

Thus, may be introduce something like this:

https://github.com/soywod/iris.vim/blob/master/autoload/iris/ui.vim#L68

    if exists('g:iris_format_mail') && g:iris_format_mail
        let p = 0
        for i in split(email, "\n")
            call append(p, i)
            call setpos('.', [0, p, 0, 0, ])
            normal! Vgq
            let p = getpos('.')[1] + 1
        endfor
    else
        call append(0, split(email, "\n"))
    endif

Or may be there's a better way?

**Comment by soywod** [comment]
Could you give me:

- Your vim/neovim version
- Your OS
- An example of what you see (the formatted and the raw data)?

**Comment by 097115** [comment]
> Your vim/neovim version

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 13 2020 18:40:36)
macOS version
Included patches: 1-569

> Your OS

macOS 10.11

> An example of what you see (the formatted and the raw data)?

Again, you realize you suggest me to paste some private data here, right? :)

Anyway, my point was the following: if an email contains a long line, it will be appended to the `IRIS-PREVIEW` buffer [as is](https://github.com/soywod/iris.vim/blob/master/autoload/iris/ui.vim#L68). Now, imagine running your Vim in a terminal with some 150 columns, in that case reading such long lines could be really quite a pain.

Now, my suggestion was to add some code that will optionally format (`:h gq`) lines from an email after appending them to the `IRIS-PREVIEW` buffer one by one.

It was just a thought, and probably there's a better way to achieve that :)

**Comment by soywod** [comment]
I understand, it's a very good point :) I will check this after work today.

**Comment by soywod** [comment]
I did some experiment, a `normal! ggVGgq` triggered on `iris-preview` buffer load seems to do the trick. I don't know if it's really what you had in mind. What I can do is to push on a branch so you can try?

For the global variable I was thinking more about sth like `g:iris_preview_textwidth`, since it's related to the `textwidth` Vim's property.

**Comment by 097115** [comment]
Applying `gq` to the whole buffer is wrong :) (by the way, you don't need `V` in this case, `gggqG` is enough: go top, start formatting, to the last line).

Imagine an email having some code, for instance: then, formatting the whole body  will simply mix everything up. While applying formatting line-by-line will only wrap long lines, and won't destroy anything else.

**Comment by soywod** [comment]
I have other bugs / features to do first, then I will take care of this one. Feel free to propose a PR :) the piece of code you have seems way enough.

**Comment by 097115** [comment]
No problem :)

As for a PR, then sorry, I'm not a programmer at all, don't want to make a mess :)

**Comment by soywod** [comment]
`Iris.vim` is no longer maintained since it has moved, see https://github.com/soywod/iris.vim/issues/46. Thank you for your interest in this project!
