### ISSUE TITLE
Having trouble with decrypt command

### ISSUE THREAD

**Issue by jsatk** [soywod/iris.vim#36]
If I leave these out of my `~/.vimrc` and manually enter the password it works fine.

```
let g:iris_imap_passwd_filepath = ~/
let g:iris_smtp_passwd_filepath = ~/
```

But if I add them it it fails.

I encrypted via 

```
gpg --encrypt password_file
```

I looked up the command used in Iris and ran it on the file `gpg --decrypt --batch --no-tty -q` and it works fine.

So I've confirmed my password works and I can decrypt the password file with the same command used in Iris. But I keep getting an authentication failure. Which makes me think something isn't being formatted correct.

I tried the file with bot a new line ending and w/o it. Same result. 😕

**Comment by soywod** [comment]
`g:iris_imap_passwd_filepath` and `g:iris_smtp_passwd_filepath` should be a file path to your `.gpg` file, not a folder. For eg me I have a `gmail.gpg` in my documents, so I have in my `.vimrc`:

```viml
let g:iris_imap_passwd_filepath = ~/Documents/gmail.gpg
```

Hope it helps.

**Comment by jsatk** [comment]
That's 100% it. `~` doesn't work. Has to be absolute path. Thanks.
