### ISSUE TITLE
Cant send emails

### ISSUE THREAD

**Issue by vushu** [soywod/iris.vim#38]
I can fully fetch emails but having trouble sending and getting following message:
`Iris: api: '[Errno -5] No address associated with hostname'    `

I'm am using outlook 365

**Comment by soywod** [comment]
It sounds like a misconfiguration. Did you follow the [SMTP section](https://github.com/soywod/iris.vim#smtp-required) in the README?

**Comment by soywod** [comment]
Here how you should set up your account:

> Server Address: smtp.office365.com
> Username: Your Office 365 Address (e.g. example@yourdomain.com)
> Password: Your Office 365 Password
> Port Number: 587 (With TLS)
> Authentication: Required
> Sending Limits: 10,000 Emails a day

**Comment by soywod** [comment]
`Iris.vim` is no longer maintained since it has moved, see https://github.com/soywod/iris.vim/issues/46. Thank you for your interest in this project!
