### ISSUE TITLE
data_raw not working properly in windows

### ISSUE THREAD

**Issue by lygamac** [soywod/iris.vim#39]
In windows iris won't even try to log in and the last message is `selecting folder...`.

What is expected is that it shows `logged in`. But it's not showing because

```
function! s:handle_data(data_raw)

  if empty(a:data_raw)
  call iris#utils#log("here")    <---- vim outputs this message
  return
  endif
  let data = json_decode(a:data_raw)
  if !data.success
    return iris#utils#elog("api: " . string(data.error))

  endif

  if data.type == "login"
    call iris#cache#write("folders", data.folders)
    call iris#utils#log("logged in!")        <----- This is expected
```
`data_raw` is empty.

**Comment by soywod** [comment]
`Iris.vim` is no longer maintained since it has moved, see https://github.com/soywod/iris.vim/issues/46. Thank you for your interest in this project!
