### ISSUE TITLE
Problem initializing mailbox - likely due to large mailbox

### ISSUE THREAD

**Issue by seanrmurphy** [soywod/iris.vim#4]
As mentioned in #3, I have had a problem initializing mailbox from office365 and obtain the following error in Iris.

![Screenshot from 2020-05-29 14-17-32](https://user-images.githubusercontent.com/540360/83264529-8081bb80-a1c0-11ea-9dd0-e7417a96acf8.png)

I believe that the issue is simply that my mailbox is quite large and office365 is refusing to provide all non deleted UIDs.

I found this issue which could be related:

mscdex/node-imap#44

I also note that if I modify the logic in `get_last_seq()` to focus on content since yesterday, it seems to work - at least retrieving the mail since yesterday.

```
def get_last_seq():
    today = datetime.datetime.today()
    interval = datetime.timedelta(days=1)
    yesterday = (today - interval).strftime('%d-%b-%Y')
    # search = _imap.search(['NOT', 'DELETED', '1:*'])
    search = _imap.search(['NOT', 'DELETED', 'SINCE', yesterday])
    fetch = _imap.fetch(search, ['UID'])
    try:
        return fetch.popitem()[0]
    except:
        return 0
```

I don't actually know how large my inbox is right now - it's not clear from Outlook Web Access.
I will find out and update.

Also, I will add a filter to ignore the `INBOX`, so it should skip on to a smaller mailbox and report.

**Comment by soywod** [comment]
`'SINCE', yesterday` works only if you receive mails every day, we need to find sth more generic. I will investigate. Thank you for your research, it's helpful!

**Comment by seanrmurphy** [comment]
Sure - the point was to check if the `fetch()` works for a more limited set of results - it does. I was not suggesting this as a general solution; just trying to understand problem space.

**Comment by soywod** [comment]
The `select_folder` method returns the next UID that should be used for the next message, so we can take this as the `last_seq`. I tried and it seems to work well. I test a bit more, update the doc and let you know when it's ready.
