### ISSUE TITLE
Can't select folder if more than 10

### ISSUE THREAD

**Issue by roxchgt** [soywod/iris.vim#41]
It's not common, but if there's more than 10 folders, then the indexes greater than 9 can't be selected!

https://github.com/soywod/iris.vim/blob/4e5e598056f9548a00f947f73959c9a0e1385bc9/autoload/iris/ui.vim#L43

**Comment by soywod** [comment]
It's true. This can be avoided by using fzf as mentioned in the [README](https://github.com/soywod/iris.vim#folders). I will find an other way. Thank you!

**Comment by roxchgt** [comment]
using alphabetical indexes liek `Folder1[0], ... , Folder10[9], Folder11[A],...` would be a quick workaround.

**Comment by soywod** [comment]
`Iris.vim` is no longer maintained since it has moved, see https://github.com/soywod/iris.vim/issues/46. Thank you for your interest in this project!
