### ISSUE TITLE
"select-folder" error : NoneType object is not subscriptable" during start-up 

### ISSUE THREAD

**Issue by gt00x** [soywod/iris.vim#44]
I received the following error message during start of :Iris.  

_Send: {"success": false, "type": "select-folder", "error": "'NoneType' object is not subscriptable"}._

The lines just before: 
[2021-03-04 21:12:23] ([(b'TEXT', b'PLAIN', (b'CHARSET', b'UTF-8', b'DELSP', b'yes', b'FORMAT', b'flowed'), None, None, b'BASE64', 1030, 21, None, None, None), (b'TEXT', b'HTML', (b'CHARSET', b'UTF-8'), None, None, b'QUOTED-PRINTABLE', 5179, 104, None, None, None)], b'ALTERNATIVE', (b'BOUNDARY', b'00000000000061aff705bc9cee06'), None, None)

[2021-03-04 21:12:23] (b'TEXT', b'PLAIN', None, None, None, b'7BIT', 28, 1, None, None, None)

From a quick search, this error is triggered when: Python objects with the value None cannot be accessed using indexing. 

In the "iris-api.log", I could see that this happens when the login was ok and it was selecting/reading the Inbox folder. When I then used ':IrisFolder' or gf  to select another folder, it worked for some folders. 

For me the issue started when I had one plain text test email on the top of my Inbox list. **I removed that email** and it made it work again. 

From the iris-api.log I could see that this message adds "None" for most fields that "Iris" processes for this email... and that make it fail. (This is my assumption, after it just started working again.)

(I like this project ... unfortunately there are still a few missing features or bugs to fix... I hope you have time again at some point ...  I am not a programmer unfortunately. )

Cheers

**Comment by soywod** [comment]
`Iris.vim` is no longer maintained since it has moved, see https://github.com/soywod/iris.vim/issues/46. Thank you for your interest in this project!
